// lib/products.ts
import { Product } from '@/types'

export const products: Product[] = [
  // ── IKAN SEGAR ──────────────────────────────────────────────
  {
    id: 'ikan-kakap-merah',
    name: 'Kakap Merah Segar',
    slug: 'kakap-merah-segar',
    category: 'ikan-segar',
    description: 'Kakap merah segar pilihan langsung dari nelayan. Daging tebal, cocok untuk dibakar, goreng, atau dibuat sup. Dibersihkan & siap masak.',
    price: 85000,
    unit: 'kg',
    stock: 50,
    images: [
      'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.8,
    reviewCount: 124,
    tags: ['bakar', 'goreng', 'sup'],
  },
  {
    id: 'ikan-gurame',
    name: 'Gurame Segar',
    slug: 'gurame-segar',
    category: 'ikan-segar',
    description: 'Gurame segar pilihan, ukuran 500-700 gram per ekor. Cocok untuk gurame bakar, asam manis, atau steam. Sudah dibersihkan.',
    price: 65000,
    unit: 'kg',
    stock: 30,
    images: [
      'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.7,
    reviewCount: 89,
    tags: ['bakar', 'asam manis', 'steam'],
  },
  {
    id: 'ikan-tongkol',
    name: 'Tongkol Segar',
    slug: 'tongkol-segar',
    category: 'ikan-segar',
    description: 'Tongkol segar berkualitas, cocok untuk tongseng, pindang, atau digoreng. Daging padat dan lezat.',
    price: 45000,
    unit: 'kg',
    stock: 40,
    images: [
      'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: false,
    rating: 4.5,
    reviewCount: 56,
    tags: ['goreng', 'pindang', 'tongseng'],
  },
  {
    id: 'ikan-bawal',
    name: 'Bawal Putih Segar',
    slug: 'bawal-putih-segar',
    category: 'ikan-segar',
    description: 'Bawal putih premium, daging lembut dan gurih. Sangat cocok untuk dibakar dengan bumbu kecap atau steam saus tiram.',
    price: 120000,
    unit: 'kg',
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.9,
    reviewCount: 201,
    tags: ['premium', 'bakar', 'steam'],
  },

  // ── UDANG ────────────────────────────────────────────────────
  {
    id: 'udang-vaname',
    name: 'Udang Vaname Segar',
    slug: 'udang-vaname-segar',
    category: 'udang',
    description: 'Udang vaname segar size 50-60 ekor/kg. Segar dari tambak, cocok untuk dibakar, saus tiram, atau digoreng tepung.',
    price: 75000,
    unit: 'kg',
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.8,
    reviewCount: 312,
    tags: ['bakar', 'goreng', 'saus tiram'],
  },
  {
    id: 'udang-windu',
    name: 'Udang Windu Jumbo',
    slug: 'udang-windu-jumbo',
    category: 'udang',
    description: 'Udang windu jumbo size 20-30 ekor/kg. Ukuran besar, daging tebal, cocok untuk sajian premium. Disajikan segar dari kolam.',
    price: 140000,
    unit: 'kg',
    stock: 25,
    images: [
      'https://images.unsplash.com/photo-1559642703-338577f16a0f?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1559642703-338577f16a0f?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.9,
    reviewCount: 178,
    tags: ['premium', 'jumbo', 'bakar'],
  },

  // ── CUMI ─────────────────────────────────────────────────────
  {
    id: 'cumi-segar',
    name: 'Cumi-cumi Segar',
    slug: 'cumi-cumi-segar',
    category: 'cumi',
    description: 'Cumi segar pilihan, bersih dan tidak berbau. Cocok untuk cumi bakar, cumi hitam, goreng tepung, atau saus padang.',
    price: 70000,
    unit: 'kg',
    stock: 35,
    images: [
      'https://images.unsplash.com/photo-1526081347589-7152f152a48a?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1526081347589-7152f152a48a?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.7,
    reviewCount: 145,
    tags: ['bakar', 'hitam', 'goreng tepung'],
  },
  {
    id: 'sotong-segar',
    name: 'Sotong Segar',
    slug: 'sotong-segar',
    category: 'cumi',
    description: 'Sotong segar berkualitas. Lebih besar dari cumi biasa, daging tebal dan gurih. Cocok untuk dimasak bumbu rica atau bakar.',
    price: 90000,
    unit: 'kg',
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1598449353-7f97a5a68a1c?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1598449353-7f97a5a68a1c?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: false,
    rating: 4.6,
    reviewCount: 67,
    tags: ['rica', 'bakar'],
  },

  // ── KEPITING / RAJUNGAN ──────────────────────────────────────
  {
    id: 'kepiting-bakau',
    name: 'Kepiting Bakau Segar',
    slug: 'kepiting-bakau-segar',
    category: 'kepiting-rajungan',
    description: 'Kepiting bakau segar, ukuran 300-500 gram/ekor. Daging penuh dan segar. Cocok untuk saus padang, kepiting saus tiram, atau rebus.',
    price: 160000,
    unit: 'kg',
    stock: 15,
    images: [
      'https://images.unsplash.com/photo-1559742811-822873691df8?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1559742811-822873691df8?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: true,
    rating: 4.9,
    reviewCount: 234,
    tags: ['premium', 'saus padang', 'rebus'],
  },
  {
    id: 'rajungan-segar',
    name: 'Rajungan Segar',
    slug: 'rajungan-segar',
    category: 'kepiting-rajungan',
    description: 'Rajungan segar laut, ukuran sedang. Daging manis dan lembut. Cocok untuk tumis rajungan, sup, atau digoreng.',
    price: 110000,
    unit: 'kg',
    stock: 20,
    images: [
      'https://images.unsplash.com/photo-1562944047-b4af0a6c8d95?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1562944047-b4af0a6c8d95?w=400',
    weight: 1000,
    isFresh: true,
    isFrozen: false,
    isPopular: false,
    rating: 4.7,
    reviewCount: 89,
    tags: ['tumis', 'sup'],
  },

  // ── OLAHAN / FROZEN ──────────────────────────────────────────
  {
    id: 'udang-tepung-frozen',
    name: 'Udang Goreng Tepung Frozen',
    slug: 'udang-goreng-tepung-frozen',
    category: 'olahan-frozen',
    description: 'Udang goreng tepung siap goreng. Tinggal goreng 3-5 menit, langsung krispi dan enak. Isi ±20 pcs/pack. Simpan di freezer.',
    price: 45000,
    unit: 'pack',
    stock: 100,
    images: [
      'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400',
    weight: 500,
    isFresh: false,
    isFrozen: true,
    isPopular: true,
    rating: 4.6,
    reviewCount: 456,
    tags: ['praktis', 'frozen', 'siap goreng'],
  },
  {
    id: 'bakso-ikan-frozen',
    name: 'Bakso Ikan Premium',
    slug: 'bakso-ikan-premium',
    category: 'olahan-frozen',
    description: 'Bakso ikan homemade dengan bahan ikan segar pilihan. Kenyal, gurih, bebas pengawet. Isi ±25 pcs/pack. Bisa untuk kuah atau goreng.',
    price: 38000,
    unit: 'pack',
    stock: 80,
    images: [
      'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    weight: 400,
    isFresh: false,
    isFrozen: true,
    isPopular: true,
    rating: 4.5,
    reviewCount: 321,
    tags: ['homemade', 'frozen', 'bebas pengawet'],
  },
  {
    id: 'otak-otak-ikan',
    name: 'Otak-otak Ikan Segar',
    slug: 'otak-otak-ikan-segar',
    category: 'olahan-frozen',
    description: 'Otak-otak ikan tenggiri asli, dibungkus daun pisang. Dipanggang segar. Isi 10 pcs/pack. Disajikan dengan saus kacang khas.',
    price: 35000,
    unit: 'pack',
    stock: 60,
    images: [
      'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
    weight: 300,
    isFresh: false,
    isFrozen: true,
    isPopular: true,
    rating: 4.8,
    reviewCount: 567,
    tags: ['tradisional', 'otak-otak', 'panggang'],
  },
  {
    id: 'kerupuk-udang',
    name: 'Kerupuk Udang Homemade',
    slug: 'kerupuk-udang-homemade',
    category: 'olahan-frozen',
    description: 'Kerupuk udang asli buatan sendiri, renyah dan gurih. Bahan udang segar tanpa MSG. Per pack 200 gram, tinggal goreng.',
    price: 25000,
    unit: 'pack',
    stock: 150,
    images: [
      'https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=400',
    weight: 200,
    isFresh: false,
    isFrozen: false,
    isPopular: false,
    rating: 4.4,
    reviewCount: 189,
    tags: ['kerupuk', 'homemade', 'tanpa MSG'],
  },
]

export const categories = [
  { id: 'semua',            label: 'Semua Produk',      emoji: '🐟' },
  { id: 'ikan-segar',       label: 'Ikan Segar',         emoji: '🐠' },
  { id: 'udang',            label: 'Udang',              emoji: '🦐' },
  { id: 'cumi',             label: 'Cumi-cumi',          emoji: '🦑' },
  { id: 'kepiting-rajungan',label: 'Kepiting & Rajungan',emoji: '🦀' },
  { id: 'olahan-frozen',    label: 'Olahan & Frozen',    emoji: '❄️' },
]

export function getProductsByCategory(category: string): Product[] {
  if (category === 'semua') return products
  return products.filter(p => p.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getPopularProducts(): Product[] {
  return products.filter(p => p.isPopular)
}
